generator:
  class: sfPropelGenerator
  param:
    model_class:           axCronTask
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              axCronTask
    plural:                axCronTasks
    route_prefix:          ax_cron_task
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ =id, name, is_active, is_running, _last_run ]
        object_actions:
          _edit: ~
          _delete: ~
          log: { action: log }
      filter:
        display: [ name, is_active ]
      form:    ~
      edit:    ~
      new:     ~
